version: '3.8'

services:
  fiaptechchallengefase2.db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 102030
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - fiap-network

  fiaptechchallengefase2.api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - fiap-network
    depends_on:
      - fiaptechchallengefase2.db

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - fiap-network
    depends_on:
      - fiaptechchallengefase2.api
    

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    links:
      - fiaptechchallengefase2.db
    environment:
      DB_SERVER_HOST: fiaptechchallengefase2.db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030
      POSTGRES_DB: zabbix
    depends_on:
      - fiaptechchallengefase2.db
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export
    networks:
      - fiap-network
    ports:
      - '10051:10051'

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
      ALLOWED_HOSTS: zabbix-server
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
    privileged: true
    networks:
      - fiap-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    environment:
      DB_SERVER_HOST: fiaptechchallengefase2.db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "America/Sao_Paulo"
    depends_on:
      - fiaptechchallengefase2.db
      - zabbix-server
    ports:
      - '8081:8080'
      - '443:8443'
    networks:
      - fiap-network
    links:
      - fiaptechchallengefase2.db
    volumes:
      - zabbix-web-data:/usr/share/zabbix
  
  prometheus:
    image: prom/prometheus
    volumes:
      - "./src/WebApi/Fiap.TechChallenge.Fase1.WebAPI/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - fiap-network
    ports:
      - 9090:9090
    depends_on:
      - fiaptechchallengefase2.api
networks:
  fiap-network:
    driver: bridge

volumes:
  grafana_storage: {}
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:
