global:
  scrape_interval: 10s
scrape_configs:
 - job_name: FiapMetrics
   metrics_path: /metrics 
   static_configs:
    - targets: ['192.168.15.6:8080']
 - job_name: 'zabbix'
   static_configs:
    - targets: ['zabbix-exporter:9270']