{
 "title": "Fiap Monitoramento",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "zabbix-agent" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Utilização Memoria RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "zabbix-agent" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Status API",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.15.6:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Último Minuto.",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Última Hora.",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Últimas 24h.",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência Média por Requisição",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_milliseconds_bucket[1m])) by (le)) / 1000",
     "legendFormat": "Latencia em Segundos"
    }
   ]
  },
  {
   "title": "Latência Percentil 95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_milliseconds_bucket[1m])) by (le)) / 1000",
     "legendFormat": "Latencia em Segundos"
    }
   ]
  },
  {
   "title": "Latência Percentil 99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_milliseconds_bucket[1m])) by (le)) / 1000",
     "legendFormat": "Latencia em Segundos"
    }
   ]
  }
 ]
}